In [2]:
import tensorflow as tf

c:\Users\roseh\Desktop\study\deep_learning\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\Users\roseh\Desktop\study\deep_learning\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\Users\roseh\Desktop\study\deep_learning\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\Users\roseh\Desktop\study\deep_lea

In [3]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1], name='weight1'))
w2 = tf.Variable(tf.random_normal([1], name='weight2'))
w3 = tf.Variable(tf.random_normal([1], name='weight3'))
b = tf.Variable(tf.random_normal([1], name='bias'))
hypothesis = x1*w1 + x2*w2 + x3*w3 + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val,_ = sess.run([cost, hypothesis, train], feed_dict={x1:x1_data, x2:x2_data, x3:x3_data, Y:y_data})

    if step%10 == 0:
        print(step, "cost:", cost_val, "\nprediction:\n", hy_val)

#what if input range is (1,2000)?
#this code is fucking terrible

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.
0 cost: 13065.911 
prediction:
 [55.662815 58.897106 62.293903 67.97488  42.493187]
10 cost: 19.925304 
prediction:
 [156.68611 180.3513  181.94832 198.27702 135.13882]
20 cost: 19.703161 
prediction:
 [156.97508 180.73027 182.30531 198.66725 135.43456]
30 cost: 19.60099 
prediction:
 [156.9593  180.74287 182.30133 198.66437 135.45079]
40 cost: 19.49939 
prediction:
 [156.94264 180.75433 182.29628 198.66032 135.46614]
50 cost: 19.398283 
prediction:
 [156.92606 180.76578 182.29124 198.65631 135.48149]
60 cost: 19.297752 
prediction:
 [156.90948 180.77716 182.2862  198.65228 135.49677]
70 cost: 19.197796 
prediction:
 [156.89296 180.78851 182.28119 198.64825 135.512  ]
80 cost: 19.098392 
prediction:
 [156.8765  180.79984 182.27618 198.64426 135.52719]
90 cost: 18.999504 
prediction:
 [156.86008 180.81114 182.27122 198.64027 135.54236]
100 cost: 18.901134 
prediction:


In [4]:
#we can use matrix
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]

y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

X = tf.placeholder(tf.float32, shape=[None, 3]) #None means n
Y = tf.placeholder(tf.float32, shape=[None, 1]) #x_data is n*3 matrtix

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X:x_data, Y:y_data}) 
    
    if step%10 == 0:
        print(step, "cost:", cost_val, "\nprediction:\n", hy_val)

0 cost: 20561.998 
prediction:
 [[23.232944]
 [32.411625]
 [29.693514]
 [31.933262]
 [26.08673 ]]
10 cost: 0.81347543 
prediction:
 [[150.08278]
 [184.87077]
 [179.91667]
 [195.52217]
 [142.37373]]
20 cost: 0.62287223 
prediction:
 [[150.46918]
 [185.33029]
 [180.372  ]
 [196.01765]
 [142.7233 ]]
30 cost: 0.62052983 
prediction:
 [[150.47292]
 [185.32993]
 [180.37418]
 [196.01968]
 [142.72209]]
40 cost: 0.6181983 
prediction:
 [[150.47551]
 [185.3282 ]
 [180.37498]
 [196.02022]
 [142.71985]]
50 cost: 0.61587214 
prediction:
 [[150.47807]
 [185.32643]
 [180.37576]
 [196.02074]
 [142.71758]]
60 cost: 0.61356795 
prediction:
 [[150.48062]
 [185.32468]
 [180.37654]
 [196.02126]
 [142.71532]]
70 cost: 0.61127603 
prediction:
 [[150.48318]
 [185.32294]
 [180.37735]
 [196.02179]
 [142.71309]]
80 cost: 0.6089865 
prediction:
 [[150.48573]
 [185.32118]
 [180.37814]
 [196.02231]
 [142.71083]]
90 cost: 0.6067227 
prediction:
 [[150.48827]
 [185.31946]
 [180.37892]
 [196.02281]
 [142.7086 ]]
100 c

In [5]:
import numpy as np

xy = np.loadtxt('data\data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:,:-1]
x_len = len(x_data)
y_data = xy[:,[-1]] #power of numpy
y_len = len(y_data)

X = tf.placeholder(tf.float32, shape=[None, 3]) #None means n
Y = tf.placeholder(tf.float32, shape=[None, 1]) #x_data is n*3 matrtix

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X:x_data, Y:y_data}) 
    
    if step%10 == 0:
        print(step, "cost:", cost_val, "\nprediction:\n", hy_val)

print("your score will be ", sess.run(hypothesis, feed_dict={X:[[100,70,101]]}))

0 cost: 33681.855 
prediction:
 [[-14.819126]
 [-24.021553]
 [-20.28772 ]
 [-23.537586]
 [-18.811642]
 [-17.09404 ]
 [-18.23237 ]
 [-14.126883]
 [-25.795698]
 [-27.823475]
 [-17.939207]
 [-21.070477]
 [-19.515995]
 [-14.615841]
 [-19.426323]
 [-25.21009 ]
 [-14.097389]
 [-21.22897 ]
 [-17.42091 ]
 [-15.241344]
 [-21.645416]
 [-23.633091]
 [-19.702324]
 [-11.591627]
 [-23.171127]]
10 cost: 37.96667 
prediction:
 [[156.4327  ]
 [181.84225 ]
 [182.53427 ]
 [197.36284 ]
 [138.19193 ]
 [ 98.68072 ]
 [147.12723 ]
 [108.470695]
 [166.62132 ]
 [150.4309  ]
 [141.3744  ]
 [136.03607 ]
 [190.0156  ]
 [159.55162 ]
 [146.69989 ]
 [183.70137 ]
 [151.77061 ]
 [177.21814 ]
 [182.33025 ]
 [163.48671 ]
 [172.26575 ]
 [169.50415 ]
 [165.17033 ]
 [161.04404 ]
 [190.17183 ]]
20 cost: 36.09454 
prediction:
 [[157.59378 ]
 [183.27222 ]
 [183.9245  ]
 [198.88895 ]
 [139.28114 ]
 [ 99.50634 ]
 [148.27779 ]
 [109.334114]
 [167.98042 ]
 [151.71944 ]
 [142.48082 ]
 [137.14685 ]
 [191.44019 ]
 [160.72095 ]
 [147.

In [13]:
filename_queue = tf.train.string_input_producer(['data\data-01-test-score.csv', 'data\data-02-test-score.csv'], shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

record_defaults = [[0.],[0.],[0.],[0.]] #define types of data fields
xy = tf.decode_csv(value, record_defaults=record_defaults) #example queue

train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size = 10)

X = tf.placeholder(tf.float32, shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None,1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)


for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch]) #we use x_batch and y_batch for feed_dict
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X:x_batch, Y:y_batch}) 
    
    if step%10 == 0:
        print(step, "cost:", cost_val, "\nprediction:\n", hy_val)

coord.request_stop()
coord.join(threads)

0 cost: 317.60687 
prediction:
 [[183.18584 ]
 [198.30292 ]
 [206.90482 ]
 [222.04994 ]
 [148.56995 ]
 [102.02493 ]
 [167.55354 ]
 [126.709404]
 [176.30154 ]
 [154.16011 ]]
10 cost: 162.25017 
prediction:
 [[165.5809 ]
 [177.23267]
 [186.09619]
 [199.40929]
 [132.5049 ]
 [ 90.22441]
 [150.61311]
 [114.15782]
 [156.65685]
 [136.01984]]
20 cost: 162.01248 
prediction:
 [[165.41158]
 [177.12135]
 [185.9372 ]
 [199.25818]
 [132.42473]
 [ 90.21011]
 [150.50694]
 [114.08608]
 [156.60117]
 [136.02528]]
30 cost: 160.62161 
prediction:
 [[165.3601 ]
 [177.15135]
 [185.9176 ]
 [199.25882]
 [132.45229]
 [ 90.27507]
 [150.51431]
 [114.09847]
 [156.67737]
 [136.15262]]
40 cost: 159.23575 
prediction:
 [[165.30965]
 [177.18214]
 [185.89905]
 [199.26047]
 [132.48047]
 [ 90.34026]
 [150.5224 ]
 [114.11132]
 [156.75406]
 [136.28017]]
50 cost: 157.8618 
prediction:
 [[165.25945 ]
 [177.21284 ]
 [185.88058 ]
 [199.26212 ]
 [132.50856 ]
 [ 90.40519 ]
 [150.53044 ]
 [114.124115]
 [156.83046 ]
 [136.40718 ]