In [1]:
import tensorflow as tf

c:\Users\roseh\Desktop\study\deep_learning\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\Users\roseh\Desktop\study\deep_learning\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\Users\roseh\Desktop\study\deep_learning\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\Users\roseh\Desktop\study\deep_lea

In [4]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1], name='weight1'))
w2 = tf.Variable(tf.random_normal([1], name='weight2'))
w3 = tf.Variable(tf.random_normal([1], name='weight3'))
b = tf.Variable(tf.random_normal([1], name='bias'))
hypothesis = x1*w1 + x2*w2 + x3*w3 + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val,_ = sess.run([cost, hypothesis, train], feed_dict={x1:x1_data, x2:x2_data, x3:x3_data, Y:y_data})

    if step%10 == 0:
        print(step, "cost:", cost_val, "\nprediction:\n", hy_val)

#what if input range is (1,2000)?
#this code is fucking terrible

0 cost: 91402.97 
prediction:
 [-110.17315 -142.6336  -135.64297 -144.2322  -114.0232 ]
10 cost: 41.24057 
prediction:
 [157.1903  178.76003 181.00955 200.59584 131.1287 ]
20 cost: 40.21275 
prediction:
 [157.97685 179.74794 181.9609  201.63322 131.89166]
30 cost: 40.022167 
prediction:
 [157.95688 179.76636 181.95709 201.63039 131.91516]
40 cost: 39.83275 
prediction:
 [157.93454 179.7818  181.95038 201.62445 131.93636]
50 cost: 39.64425 
prediction:
 [157.91222 179.7972  181.94368 201.6185  131.95747]
60 cost: 39.456734 
prediction:
 [157.88998 179.81256 181.93703 201.6126  131.97858]
70 cost: 39.270267 
prediction:
 [157.8678  179.82785 181.93036 201.60666 131.99959]
80 cost: 39.084797 
prediction:
 [157.84569 179.84312 181.92374 201.60075 132.02055]
90 cost: 38.900288 
prediction:
 [157.82365 179.85837 181.91711 201.5949  132.04149]
100 cost: 38.71688 
prediction:
 [157.80165 179.87354 181.91052 201.589   132.06232]
110 cost: 38.534187 
prediction:
 [157.77971 179.8887  181.90395 2

In [10]:
#we can use matrix
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]

y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

X = tf.placeholder(tf.float32, shape=[None, 3]) #None means n
Y = tf.placeholder(tf.float32, shape=[None, 1]) #x_data is n*3 matrtix

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X:x_data, Y:y_data}) 
    
    if step%10 == 0:
        print(step, "cost:", cost_val, "\nprediction:\n", hy_val)

0 cost: 116172.11 
prediction:
 [[-153.5226 ]
 [-177.07298]
 [-178.19905]
 [-194.46187]
 [-133.05034]]
10 cost: 4.377894 
prediction:
 [[147.99295]
 [185.31317]
 [178.87302]
 [194.37987]
 [143.35648]]
20 cost: 3.2975578 
prediction:
 [[148.9121 ]
 [186.40492]
 [179.95549]
 [195.55786]
 [144.18663]]
30 cost: 3.2807739 
prediction:
 [[148.92172]
 [186.40355]
 [179.96088]
 [195.56291]
 [144.18301]]
40 cost: 3.2640991 
prediction:
 [[148.92856]
 [186.39886]
 [179.96297]
 [195.5644 ]
 [144.17688]]
50 cost: 3.2475228 
prediction:
 [[148.93538]
 [186.3942 ]
 [179.96506]
 [195.5659 ]
 [144.17078]]
60 cost: 3.231032 
prediction:
 [[148.94218]
 [186.38954]
 [179.96716]
 [195.5674 ]
 [144.16469]]
70 cost: 3.2146156 
prediction:
 [[148.94897]
 [186.3849 ]
 [179.96924]
 [195.56888]
 [144.1586 ]]
80 cost: 3.198299 
prediction:
 [[148.95575]
 [186.38026]
 [179.97131]
 [195.57037]
 [144.15256]]
90 cost: 3.182064 
prediction:
 [[148.96248]
 [186.37563]
 [179.97337]
 [195.57182]
 [144.14648]]
100 cost: 

In [22]:
import numpy as np

xy = np.loadtxt('data\data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:,:-1]
x_len = len(x_data)
y_data = xy[:,[-1]] #power of numpy
y_len = len(y_data)

X = tf.placeholder(tf.float32, shape=[None, 3]) #None means n
Y = tf.placeholder(tf.float32, shape=[None, 1]) #x_data is n*3 matrtix

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X:x_data, Y:y_data}) 
    
    if step%10 == 0:
        print(step, "cost:", cost_val, "\nprediction:\n", hy_val)

print("your score will be ", sess.run(hypothesis, feed_dict={X:[[100,70,101]]}))

0 cost: 5764.073 
prediction:
 [[225.82062]
 [270.30487]
 [266.84906]
 [290.37573]
 [206.25104]
 [151.90216]
 [217.57426]
 [161.55289]
 [252.24532]
 [233.23999]
 [209.54437]
 [206.14409]
 [275.82214]
 [229.60623]
 [218.41052]
 [274.209  ]
 [218.62183]
 [261.0585 ]
 [263.16776]
 [235.62996]
 [254.924  ]
 [253.52733]
 [243.21667]
 [228.0458 ]
 [280.33838]]
10 cost: 13.649261 
prediction:
 [[155.0032 ]
 [185.20053]
 [182.98785]
 [199.05055]
 [141.34305]
 [104.05877]
 [149.21979]
 [110.8866 ]
 [172.71927]
 [159.59384]
 [143.68568]
 [141.21349]
 [189.17598]
 [157.57013]
 [149.74426]
 [187.85277]
 [150.01323]
 [179.02754]
 [180.5603 ]
 [161.7158 ]
 [174.76706]
 [173.69315]
 [166.79068]
 [156.63109]
 [192.1329 ]]
20 cost: 13.316588 
prediction:
 [[154.50558]
 [184.61417]
 [182.40358]
 [198.42014]
 [140.89389]
 [103.73808]
 [148.75339]
 [110.54813]
 [172.18118]
 [159.10951]
 [143.23376]
 [140.7753 ]
 [188.56653]
 [157.05585]
 [149.2781 ]
 [187.26228]
 [149.5199 ]
 [178.46881]
 [179.97653]
 [16