In [2]:
import numpy as np

#numpy 2D array slicing
b=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(b)
print(b[:,1])
print(b[0:2,:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 2  6 10]
[[1 2 3 4]
 [5 6 7 8]]
